# Generated by Django 3.2 on 2021-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknowcms_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolioImage',
            field=models.ImageField(default='portfolio/default_portfolio_image.png', help_text='600x400 piksel olmalı.', upload_to='portfolio/tr/%Y/%m/%d/', verbose_name='Proje Görseli'),
        ),
    ]
