# Generated by Django 3.2 on 2021-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknowcms_portfolio', '0002_alter_portfolio_portfolioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolioImage',
            field=models.ImageField(default='project/default_project_image.png', help_text='600x400 piksel olmalı.', upload_to='project/tr/%Y/%m/%d/', verbose_name='Proje Görseli'),
        ),
    ]
