# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(help_text='Maximum 50 character, unique.', max_length=50, unique=True, verbose_name='Service Title')),
                ('serviceContent', ckeditor.fields.RichTextField(verbose_name='Service Content')),
                ('serviceIcon', models.CharField(default='<i class="fas fa-server fa-5x"></i>', help_text='You should paste Font Awesome Icon tag here. For icon size add fa-2x, fa-3x, fa-5x etc.. to end of the class.', max_length=50, verbose_name='Service Icon')),
                ('serviceSlug', models.SlugField(help_text='Url format of the Service Title, unique.', unique=True, verbose_name='Service Slug')),
            ],
        ),
    ]
