# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutTitle', models.CharField(default='About', help_text='Maximum 50 character, unique.', max_length=50, unique=True, verbose_name='About')),
                ('aboutContent', ckeditor.fields.RichTextField(verbose_name='About Content')),
                ('aboutImage', models.ImageField(default='about/default_about_image.svg', upload_to='about/en/', verbose_name='About Image')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactTitle', models.CharField(default='Contact', help_text='Maximum 50 character, unique.', max_length=50, unique=True, verbose_name='Contact')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Address')),
                ('googleMap', models.TextField(help_text='Paste Google Maps iFrame link here.', verbose_name='Google Maps iFrame Link')),
                ('phoneOne', models.CharField(help_text='This field is required.', max_length=20, verbose_name='Phone Number')),
                ('phoneTwo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('phoneThree', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('emailOne', models.CharField(help_text='This field is required.', max_length=40, verbose_name='E-Mail')),
                ('emailTwo', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-Mail')),
                ('emailThree', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-Mail')),
                ('facebook', models.CharField(blank=True, help_text='Paste Facebook link here.', max_length=100, null=True, verbose_name='Facebook Link')),
                ('twitter', models.CharField(blank=True, help_text='Paste Twitter link here.', max_length=100, null=True, verbose_name='Twitter Link')),
                ('instagram', models.CharField(blank=True, help_text='Paste Instagram link here.', max_length=100, null=True, verbose_name='Instagram Link')),
                ('youtube', models.CharField(blank=True, help_text='Paste Youtube link here.', max_length=100, null=True, verbose_name='Youtube Link')),
                ('linkedin', models.CharField(blank=True, help_text='Paste Linkedin link here.', max_length=100, null=True, verbose_name='Linkedin Link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqTitle', models.TextField(verbose_name='Question')),
                ('faqContent', models.TextField(verbose_name='Answer')),
                ('faqSlug', models.SlugField(help_text='Url format of the Question, unique.', verbose_name='Question Slug')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyTitle', models.CharField(default='Privacy Policy', help_text='Maximum 50 character, unique.', max_length=50, verbose_name='Policy Title')),
                ('policyContent', ckeditor.fields.RichTextField(verbose_name='Policy Content')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
    ]
