# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutTitle', models.CharField(default='Hakkımızda', help_text='Maksimum 50 karakter, benzersiz.', max_length=50, unique=True, verbose_name='Hakkımızda')),
                ('aboutContent', ckeditor.fields.RichTextField(verbose_name='Hakkımızda Yazısı')),
                ('aboutImage', models.ImageField(default='about/default_about_image.svg', upload_to='about/tr/', verbose_name='Hakkımızda Görseli')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactTitle', models.CharField(default='İletişim', help_text='Maksimum 50 karakter, benzersiz.', max_length=50, unique=True, verbose_name='İletişim')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Adres')),
                ('googleMap', models.TextField(help_text='Google Maps iFrame Linkini buraya yapıştırın.', verbose_name='Google Maps iFrame Link')),
                ('phoneOne', models.CharField(help_text='Bu alan zorunludur.', max_length=20, verbose_name='Telefon Numarası')),
                ('phoneTwo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('phoneThree', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('emailOne', models.CharField(help_text='Bu alan zorunludur.', max_length=40, verbose_name='E-Posta')),
                ('emailTwo', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-Posta')),
                ('emailThree', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-Posta')),
                ('facebook', models.CharField(blank=True, help_text='Facebook sayfanızın linkini buraya yapıştırın.', max_length=100, null=True, verbose_name='Facebook Link')),
                ('twitter', models.CharField(blank=True, help_text='Twitter sayfanızın linkini buraya yapıştırın.', max_length=100, null=True, verbose_name='Twitter Link')),
                ('instagram', models.CharField(blank=True, help_text='Instagram sayfanızın linkini buraya yapıştırın.', max_length=100, null=True, verbose_name='Instagram Link')),
                ('youtube', models.CharField(blank=True, help_text='Youtube sayfanızın linkini buraya yapıştırın.', max_length=100, null=True, verbose_name='Youtube Link')),
                ('linkedin', models.CharField(blank=True, help_text='Linkedin sayfanızın linkini buraya yapıştırın.', max_length=100, null=True, verbose_name='Linkedin Link')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqTitle', models.TextField(verbose_name='Soru')),
                ('faqContent', models.TextField(verbose_name='Cevap')),
                ('faqSlug', models.SlugField(help_text='Sorunun url uzantı formatı. Benzersiz.', verbose_name='Soru Uzantısı')),
            ],
            options={
                'verbose_name': 'Sıkça Sorulan Soru',
                'verbose_name_plural': 'Sıkça Sorulan Sorular',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyTitle', models.CharField(default='Kişisel Verilerin Korunması Kanunu', help_text='Maksimum 50 karakter, benzersiz.', max_length=50, verbose_name='Kanun')),
                ('policyContent', ckeditor.fields.RichTextField(verbose_name='Kanun İçeriği')),
            ],
            options={
                'verbose_name': 'Kanun',
                'verbose_name_plural': 'Kanunlar',
            },
        ),
    ]
