# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioTitle', models.CharField(help_text='Maximum 100 character, unique.', max_length=100, unique=True, verbose_name='Portfolio Title')),
                ('portfolioContent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Portfolio Content')),
                ('portfolioImage', models.ImageField(default='portfolio/default_portfolio_image.png', help_text='Should be 600x600 pixels.', upload_to='portfolio/en/%Y/%m/%d/', verbose_name='Portfolio Image')),
                ('portfolioSlug', models.SlugField(help_text='Url format of the Portfolio Title, unique.', max_length=100, unique=True, verbose_name='Portfolio Slug')),
            ],
        ),
    ]
