# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselTitle', models.CharField(help_text='Maksimum 50 karakter. Görsel içerisinde yer alan yazıdan bir kesit.', max_length=50, unique=True, verbose_name='Görsel Başlığı')),
                ('carouselImageLarge', models.ImageField(default='carousel/large/default_carouselLarge_image.png', help_text='1200x400 piksel olmalı.', upload_to='carousel/tr/large/', verbose_name='Büyük Görsel')),
                ('carouselImageMedium', models.ImageField(default='carousel/medium/default_carouselMedium_image.png', help_text='720x400 piksel olmalı.', upload_to='carousel/tr/medium/', verbose_name='Orta Büyüklük Görsel')),
                ('carouselImageSmall', models.ImageField(default='carousel/small/default_carouselSmall_image.png', help_text='575x575 piksel olmalı.', upload_to='carousel/tr/small/', verbose_name='Küçük Görsel')),
                ('carouselContent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Görsel İçeriği')),
                ('carouselBackgroundColor', models.CharField(default='#ffbd59', help_text='Örnek: #ffbd59', max_length=20, verbose_name='Arka Plan Rengi')),
                ('carouselSlug', models.SlugField(help_text='Görsel başlığının url uzantı formatı, benzersiz.', unique=True, verbose_name='Görsel Uzantısı')),
            ],
            options={
                'verbose_name': 'Anasayfa Görseli',
                'verbose_name_plural': 'Anasayfa Görselleri',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientTitle', models.CharField(help_text='Maksimum 50 karakter, benzersiz.', max_length=50, unique=True, verbose_name='Şirket Adı')),
                ('clientImage', models.ImageField(default='client/default_client_image.svg', upload_to='client/tr/', verbose_name='Şirket Logosu')),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialTitle', models.CharField(help_text='Maksimum 50 karakter, benzersiz.', max_length=50, unique=True, verbose_name='Referans Başlığı')),
                ('testimonialContent', models.TextField(verbose_name='Referans İçeriği')),
                ('testimonialImage', models.ImageField(default='testimonial/default_testimonial_image.svg', upload_to='testimonial/tr/', verbose_name='Referans Görseli')),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
            },
        ),
    ]
