# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselTitle', models.CharField(help_text='Maximum 50 character. A section of the text in the image.', max_length=100, unique=True, verbose_name='Image Title')),
                ('carouselImageLarge', models.ImageField(default='carousel/large/default_carouselLarge_image.png', help_text='Size: 1200x400 px.', upload_to='carousel/en/large/', verbose_name='Large Image')),
                ('carouselImageMedium', models.ImageField(default='carousel/medium/default_carouselMedium_image.png', help_text='Size: 720x400 px.', upload_to='carousel/en/medium/', verbose_name='Medium Image')),
                ('carouselImageSmall', models.ImageField(default='carousel/small/default_carouselSmall_image.png', help_text='Size: 575x575 px.', upload_to='carousel/en/small/', verbose_name='Small Image')),
                ('carouselContent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Carousel Content')),
                ('carouselBackgroundColor', models.CharField(default='#ffbd59', help_text='Sample: #ffbd59', max_length=20, verbose_name='Background Color')),
                ('carouselSlug', models.SlugField(help_text='Url format of the Carousel Title, unique.', max_length=100, unique=True, verbose_name='Carousel Url Format')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientTitle', models.CharField(help_text='Maximum 50 character, unique.', max_length=50, unique=True, verbose_name='Client Title')),
                ('clientImage', models.ImageField(default='client/default_client_image.svg', upload_to='client/en/', verbose_name='Client Image')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialTitle', models.CharField(help_text='Maximum 50 character, unique.', max_length=50, unique=True, verbose_name='Testimonial Title')),
                ('testimonialContent', models.TextField(verbose_name='Testimonial Content')),
                ('testimonialImage', models.ImageField(default='testimonial/default_testimonial_image.svg', upload_to='testimonial/en/', verbose_name='Testimonial Image')),
            ],
        ),
    ]
