# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerTitle', models.CharField(max_length=50, verbose_name='İş İlanı Başlığı')),
                ('careerContent', ckeditor.fields.RichTextField(verbose_name='İş İlanı İçeriği')),
                ('careerDate', models.DateTimeField(auto_now_add=True)),
                ('careerLocation', models.CharField(default='Türkiye/Edirne', max_length=50, verbose_name='İş İlanı Lokasyonu')),
                ('careerSlug', models.SlugField(help_text='İlan Başlığı + İlan Tarihi url uzantı formatı, benzersiz.', unique=True, verbose_name='İş İlanı Uzantısı')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
            },
        ),
    ]
