# Generated by Django 3.2 on 2021-04-30 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(help_text='Maksimum 50 karakter, benzersiz.', max_length=50, unique=True, verbose_name='Hizmet Başlığı')),
                ('serviceContent', ckeditor.fields.RichTextField(verbose_name='Hizmet İçeriği')),
                ('serviceIcon', models.CharField(default='<i class="fas fa-server fa-5x"></i>', help_text="Buraya Font Awesome'dan uygun bir ikonun etiketini yapıştırın. İkon boyutu için classın sonuna fa-2x, fa-3x, fa-5x eklenebilir.", max_length=50, verbose_name='Hizmet İkon')),
                ('serviceSlug', models.SlugField(help_text='Hizmet başlığının url uzantı formatı, benzersiz.', unique=True, verbose_name='Hizmet Uzantısı')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
