# Generated by Django 3.2 on 2021-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknowcms_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogImage',
            field=models.ImageField(default='blog/default_blog_image.png', help_text='600x400 piksel olmalı.', upload_to='blog/tr/%Y/%m/%d/', verbose_name='Blog Görseli'),
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
    ]
